# This is a placeholder for the official AWS EBS CSI Driver Helm Chart values or Manifest
# In production, use Helm: helm install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
